### ISSUE TITLE
Problem with lab 09 pipeline job

### ISSUE THREAD

**Issue by JisenRen** [MicrosoftLearning/mslearn-azure-ml#12] opened 2023-05-07 19:30 UTC
# Module: 00
#### Step: 00

Pipeline job fails for lab 09: Run a pipeline job

Repro steps:

1. This notebook did not create a datastore `diabetes-data`, so the pipeline job would fail to find the input at the first step.
2. Even if the problem above is fixed, the pipeline job still fails at the `to_csv` step, due to that the output path does not exist.

**Comment by o-rod** [comment] 2023-05-07 20:54
Having similar issue.  Pipeline fails on the "Prepare training data" component.
J Notebook file:  Run a pipeline job.ipynb

Error/stack trace taken from std_log.txt of component [Prepare training data] : 

  File "prep-data.py", line 16, in main
    output_df = normalized_data.to_csv((Path(args.output_data) / "diabetes.csv"), index = False)
.
.
.

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/azureml/cr/j/ab921d072ea34ac2b7839a52ab90f586/cap/data-capability/wd/output_data/output_data/diabetes.csv'

**Comment by madiepev** [comment] 2023-05-08 09:55
The dataset is created with the setup script. Did you run the setup script before running the notebook?

**Comment by JisenRen** [comment] 2023-05-08 11:12
> The dataset is created with the setup script. Did you run the setup script before running the notebook?

I ran setup.sh before running the notebook in ML workspace

**Comment by JisenRen** [comment] 2023-05-08 11:12
> Having similar issue. Pipeline fails on the "Prepare training data" component. J Notebook file: Run a pipeline job.ipynb
> 
> Error/stack trace taken from std_log.txt of component [Prepare training data] :
> 
> File "prep-data.py", line 16, in main output_df = normalized_data.to_csv((Path(args.output_data) / "diabetes.csv"), index = False) . . .
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/mnt/azureml/cr/j/ab921d072ea34ac2b7839a52ab90f586/cap/data-capability/wd/output_data/output_data/diabetes.csv'

Exactly the same problem.

**Comment by madiepev** [comment] 2023-05-08 11:31
I just ran the notebook successfully and haven't been able to reproduce your error. Ensure you're running the setup script from the folder Labs/09 and that you use the Python 3.8 - AzureML kernel as described in the instructions.
You describe that the "datastore" diabetes.csv isn't created. However, the script creates a "dataset" with that name. The pipeline also expects a dataset as input, not a datastore. I wonder what you mean with that you fixed the problem. If you created a datastore manually, that won't fix the problem. You need a dataset of URI_file type.

**Comment by o-rod** [comment] 2023-05-08 15:56
1. deleted ML resource group to start fresh
2. followed all steps given here to recreate ML resource group [US east]:  https://microsoftlearning.github.io/mslearn-azure-ml/Instructions/09-Run-pipelines.html
3. the correct setup.sh script was executed
4. verified existence of data asset  in ML studio ( ML Studio : Assets --> Data) and proper Python version[Python 3.8 - Azure ML] before proceeding any further
5.  cloned the lab material and ran the steps in the notebook 1 by 1
6.  pipeline job failed in the same component [prepare training data]
7.  stack trace given below taken from the job [diabetes_classification] : ML Studio : Assets --> Jobs

------------------------

Execution failed. User process 'python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error: Traceback (most recent call last):
  File "prep-data.py", line 68, in <module>
    main(args)
  File "prep-data.py", line 16, in main
    output_df = normalized_data.to_csv((Path(args.output_data) / "diabetes.csv"), index = False)
  File "/azureml-envs/sklearn-0.24.1/lib/python3.7/site-packages/pandas/core/generic.py", line 3170, in to_csv
    formatter.save()
  File "/azureml-envs/sklearn-0.24.1/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 190, in save
    compression=dict(self.compression_args, method=self.compression),
  File "/azureml-envs/sklearn-0.24.1/lib/python3.7/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/azureml/cr/j/201ddcb1202c4f398c0be90b9647c376/cap/data-capability/wd/output_data/output_data/diabetes.csv'

**Comment by JisenRen** [comment] 2023-05-08 19:14
> 

I tried the same steps and got exactly the same errors.

**Comment by madiepev** [comment] 2023-05-09 11:21
The issue seems to be caused by the type of data input and output. If you set the data types to folder for both steps it should work again. I'm testing the updated code before pushing the changes.

**Closed** 2023-05-30 13:39 UTC
