### ISSUE TITLE
Lab Issue with Data Asset

### ISSUE THREAD

**Issue by dravidshankar** [MicrosoftLearning/mslearn-azure-ml#90] opened 2024-06-06 20:32 UTC
# Module: 00
#### Step: 00

Lab 3,10 and 11 instructions:
 
Read the following steps to resolve the issues.

command to clone repo:
 
git clone https://github.com/MicrosoftLearning/mslearn-azure-ml.git azure-ml-labs
 
 
Data command:
 
cd azure-ml-labs/Labs/09
 
az ml data create --type uri_file --name "diabetes-data" --path ./data/diabetes.csv -w <ml-workspace-name> --resource-group <resource-group-name>

**Comment by afelix-95** [comment] 2024-07-24 05:02
All the labs mentioned are working as intended. Closing this issue as no repro.

**Closed by afelix-95** 2024-07-24 05:02 UTC
